create index IDX_INVNTRYBATCH_VLD_EXPIRY on INVNTRYBATCH(VLD,BEXP);

ALTER TABLE USERTOKEN
ADD `DESCRIPTION` varchar(1024) DEFAULT NULL AFTER `ACCESSKEY`,
ADD `TOKEN_TYPE` enum('LOGIN', 'BULLETIN_BOARD', 'PERSONAL_ACCESS_TOKEN') DEFAULT 'LOGIN' AFTER `DESCRIPTION`,
ADD `CREATED_ON` datetime DEFAULT NULL AFTER `TOKEN_TYPE`;

update USERTOKEN set TOKEN_TYPE = 'LOGIN' where ACCESSKEY is NULL;
update USERTOKEN set TOKEN_TYPE = 'BULLETIN_BOARD' where ACCESSKEY is not NULL;

ALTER TABLE MATERIAL MODIFY COLUMN NAME VARCHAR(512), MODIFY COLUMN UNAME VARCHAR(512);