create index IDX_USERLOGINHISTORY_USERID on USERLOGINHISTORY(USERID);

CREATE TABLE `logistimo`.`TRANSPORTERS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `SDID` BIGINT(20) NOT NULL,
  `API_METADATA_ID` BIGINT(20) DEFAULT NULL,
  `COUNTRY` VARCHAR(255) DEFAULT NULL,
  `STATE` VARCHAR(255) DEFAULT NULL,
  `DISTRICT` VARCHAR(255) DEFAULT NULL,
  `TALUK` VARCHAR(255) DEFAULT NULL,
  `CITY` VARCHAR(255) DEFAULT NULL,
  `COUNTRY_ID` CHAR(36) DEFAULT NULL,
  `STATE_ID` CHAR(36) DEFAULT NULL,
  `DISTRICT_ID` CHAR(36) DEFAULT NULL,
  `TALUK_ID` CHAR(36) DEFAULT NULL,
  `CITY_ID` CHAR(36) DEFAULT NULL,
  `STREET_ADDRESS` VARCHAR(255) DEFAULT NULL,
  `PIN_CODE` VARCHAR(255) DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(30) NOT NULL,
  `VEHICLE` VARCHAR(255) DEFAULT NULL,
  `TYPE` VARCHAR(20) DEFAULT NULL,
  `IS_API_SUPPORTED` bit(1) DEFAULT NULL,
  `ENDPOINT` VARCHAR(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` VARCHAR(25) DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `UPDATED_BY` VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `logistimo`.`TRANSPORTER_API_METADATA` (
	  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	  `TSP_ID` VARCHAR(255) NOT NULL,
    `URL` VARCHAR(255) NOT NULL,
    `ACCOUNT_ID` VARCHAR(255) DEFAULT NULL,
    `SECRET` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`ID`)
);

INSERT INTO `logistimo`.`CONFIG` (`KEY`) VALUES ('transportersconfig');

CREATE TABLE `logistimo`.`DELIVERY_REQUEST` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` BIGINT(20) NOT NULL,
  `SHIPMENT_ID` VARCHAR(255) NOT NULL,
  `DOMAIN_ID` BIGINT(20) DEFAULT NULL,
  `SHIPPER_KID` BIGINT(20) DEFAULT NULL,
  `RECEIVER_KID` BIGINT(20) DEFAULT NULL,
  `CATEGORY_ID` VARCHAR(255)  DEFAULT NULL,
  `NO_OF_PACKAGES` int(11) DEFAULT NULL,
  `WEIGHT` DECIMAL(16,4) DEFAULT NULL,
  `LENGTH` DECIMAL(16,4) DEFAULT NULL,
  `BREADTH` DECIMAL(16,4) DEFAULT NULL,
  `HEIGHT` DECIMAL(16,4) DEFAULT NULL,
  `VALUE` DECIMAL(16,4) DEFAULT NULL,
  `STATUS` varchar(255)  DEFAULT NULL,
  `STATUS_UPDATED_AT` DATETIME DEFAULT NULL,
  `PICKUP_READY_BY` DATETIME DEFAULT NULL,
  `ETA` DATETIME DEFAULT NULL,
  `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `INSTRUCTIONS` VARCHAR(500) DEFAULT NULL,
  `TRANSPORTER_ID` BIGINT(20) NOT NULL,
  `TRACKING_ID` VARCHAR(255) DEFAULT NULL,
  `DELIVERY_TYPE` VARCHAR(255) DEFAULT NULL,
  `TP_REF_NUM` VARCHAR(255) DEFAULT NULL,
  `REMARKS` VARCHAR(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` VARCHAR(25) DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `UPDATED_BY` VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DELIVERY_REQUEST#1` (`SHIPMENT_ID`));

CREATE TABLE `logistimo`.`CONSIGNMENTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NUMPACKAGES` int(11) DEFAULT NULL,
  `WTKG` DECIMAL(16,4) DEFAULT NULL,
  `LENGTH` DECIMAL(16,4) DEFAULT NULL,
  `BREADTH` DECIMAL(16,4) DEFAULT NULL,
  `HEIGHT` DECIMAL(16,4) DEFAULT NULL,
  `CATEGORY` VARCHAR(255) DEFAULT NULL,
  `DECLARATION` VARCHAR(500) DEFAULT NULL,
  `VALUE` DECIMAL(16,4) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

ALTER TABLE `logistimo`.`SHIPMENT`
  ADD TRANSPORTER_PHONE VARCHAR(30) AFTER `TRANSPORTER`,
  ADD CONSIGNMENT_ID BIGINT(20) AFTER `SALES_REF_ID`,
  ADD TRANSPORTER_ID BIGINT(20) AFTER `CONSIGNMENT_ID`,
  ADD VEHICLE VARCHAR(255) AFTER `TRANSPORTER_ID`,
  ADD CUST_PICKUP BIT(1) NOT NULL DEFAULT 0 AFTER `VEHICLE`;