ALTER TABLE INVNTRY ADD COLUMN IAT DATETIME DEFAULT NULL;
ALTER TABLE DEMANDITEM ADD COLUMN FQ DECIMAL(16,4) DEFAULT NULL AFTER DQ;

UPDATE INVNTRY AS I LEFT JOIN (SELECT MIN(T) AS UT, KID, MID FROM TRANSACTION GROUP BY KID, MID) AS T ON I.KID = T.KID AND I.MID = T.MID
SET I.IAT = T.UT;

create index INVNTRYEVNTLOG_TY_ED on INVNTRYEVNTLOG(TY,ED);