ALTER TABLE `logistimo`.`INVNTRY` ADD UON DATETIME NULL;
CREATE TABLE `MATERIALMANUFACTURERS` (
  `KEY` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MATERIAL_ID` BIGINT(20) NOT NULL,
  `MFR_CODE` BIGINT(20) NOT NULL,
  `MFR_NAME` VARCHAR(255) NOT NULL,
  `MATERIAL_CODE` BIGINT(20) NOT NULL,
  `QTY` FLOAT NULL,
  PRIMARY KEY (`KEY`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;